name: Renode Tests

on:
  push:
  pull_request:

jobs:
  renode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build ESP32 Improv firmware for Renode
        run: pio test -e esp32-improv-test --without-testing --without-uploading

      - name: Run Renode tests
        uses: antmicro/renode-test-action@v4
        env:
          ESPRESENSE_BOOTLOADER: ${{ github.workspace }}/.pio/build/esp32-improv-test/bootloader.bin
          ESPRESENSE_PARTITIONS: ${{ github.workspace }}/.pio/build/esp32-improv-test/partitions.bin
          ESPRESENSE_FIRMWARE: ${{ github.workspace }}/.pio/build/esp32-improv-test/firmware.bin
        with:
          renode-revision: master
          tests-to-run: renode/tests/**/*.robot
